# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b01ffef4d877caa89f61ea3279f104fc71bde4f4b5e7ca9469b9a599d97af6e2bfe9d41309d12a5f163eec10720528ab1f0a6831728537db9e3860ce03659c71

test:
  secret_key_base: c3a9ea09949dfdb467d77fc9aacfff6a0ce182eb71f6587eaa9a67ea6a813bd9e4ef339dfe4a1ea8b1eb5019ff3e3505fdffc70300f5c095e3b37c5108c803ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_SECRET"] %>
